export enum Auth {
	LOADING = "AUTH/LOADING",
	SUCCESS = "AUTH/SUCCESS",
	ERROR = "AUTH/ERROR",
	LOGIN = "AUTH/LOGIN",
	LOGOUT = "AUTH/LOGOUT",
	SIGNUPSTATUS = "AUTH/SIGNUPSTATUS",
	RESETSTATUS = "AUTH/RESETSTATUS",
	LOGINSTATUS = "AUTH/LOGINSTATUS",
	RESETLOGINSTATUS = "AUTH/RESETLOGINSTATUS",
}
